server:
  port: 80

redis:
  distributedlock:
    address1: 127.0.0.1:6379
    address2: redis01.grr6uh.0001.cnw1.cache.amazonaws.com.cn:6379
    address3: redis02.grr6uh.0001.cnw1.cache.amazonaws.com.cn:6379